apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: account-hpa, namespace: retail }
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: account-service }
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies: [{ type: Pods, value: 1, periodSeconds: 60 }]
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: checkout-hpa, namespace: retail }
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: checkout-service }
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies: [{ type: Pods, value: 1, periodSeconds: 60 }]
