apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retail-ingress-v3
  namespace: retail
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "retail-ip"
spec:
  rules:
  - host: api.retail.example.com
    http:
      paths:
      - path: /account/*
        pathType: ImplementationSpecific
        backend: { service: { name: account-service, port: { number: 80 } } }
      - path: /auth/*
        pathType: ImplementationSpecific
        backend: { service: { name: account-service, port: { number: 80 } } }
      - path: /payments/*
        pathType: ImplementationSpecific
        backend: { service: { name: payment-service, port: { number: 80 } } }
      - path: /checkout/*
        pathType: ImplementationSpecific
        backend: { service: { name: checkout-service, port: { number: 80 } } }
      - path: /cart/*
        pathType: ImplementationSpecific
        backend: { service: { name: checkout-service, port: { number: 80 } } }
      - path: /orders/*
        pathType: ImplementationSpecific
        backend: { service: { name: loyalty-service, port: { number: 80 } } }
      - path: /loyalty/*
        pathType: ImplementationSpecific
        backend: { service: { name: loyalty-service, port: { number: 80 } } }
