apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: retail-db
  namespace: retail
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/771657108405/secrets/retail-db-password/versions/latest"
        path: "db-password"
